spring.application.name=backend

spring.datasource.url=jdbc:mysql://143.106.241.4:3306/cl204225?sslMode=DISABLED&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo&nullCatalogMeansCurrent=true
spring.datasource.username=cl204225
spring.datasource.password=cl*05102007
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true